GET http://localhost:4000/tasks

###

POST http://localhost:4000/tasks
Content-Type: application/json

{
  "id": "4",
  "description": "Task 4",
  "completed": false
}

###

PATCH http://localhost:4000/tasks/5
Content-Type: application/json

{
  "completed": true
}
